name: Test Github Action

on: [push, pull_request]

jobs:
  test-mkver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone pre repositories
        run: |
          cd ..
          git clone https://github.com/cigar666/my_manim_projects.git my_manim_projects
      - name: Test rendering example_scenes.py
        uses: ./
        id: renderer
        with:
          source_file: test/example_scenes.py
          scene_names: "Explain_Arc"
          args: "--high_quality"
          fonts_dir: test/fonts/
          extra_repos: "https://github.com/manim-kindergarten/manim_sandbox"
      - name: Save output as artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Videos_mkver
          path: ${{ steps.renderer.outputs.video_path }}
