name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      run: |
        cd ..
        mkdir you_get
        cd you_get/
        pip3 install you-get
        
    
    - name: download_videos
      id: videos
      run: |
        mkdir videos
        cd videos
        you-get -o ./videos 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
        
    
    - name: Save output as artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: download_videos
        path: ${{ steps.videos.videos }}

