name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir -p ~/you_get
        cd ~/you_get/
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/tensorflow-doc-zh/you_get"
        you-get -o ~/you_get/ 'https://youtu.be/GZBIPwdGtkk?list=PLBkISg6QfSX9HL6us70IBs9slFciFFa4W'
    
    - name: Save output as artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: download_videos
        path: ~/you_get/

