name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls 
        echo "=========================="
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ --playlist 'https://www.bilibili.com/video/BV1pg4y1i7T9'
        
        ls
        echo '============================================='
        cd you_get
        ls
        echo '=========================================='
        
        cd ../
        mkdir tensorflow-doc-zh/source/assets/videos/ImperialCollegeMath
        cp -r you_get/. tensorflow-doc-zh/source/assets/videos/ImperialCollegeMath
        cd tensorflow-doc-zh/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/assets/videos/
        git add -A
        git status 
        git commit -m "Add some videos"
        ls
        git push origin master

