name: tfplayground

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        cd ..
        git clone https://github.com/tensorflow/playground tfplay
        cd tfplay
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/tfplay"
        npm i
        npm run build
        
    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: th-pages
        FOLDER: build/dist
