name: move some videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        mkdir /tensorflow-doc-zh/videos 
        cp -r tensorflow-doc-zh/source/assets/videos/ImperialCollegeMath/. tensorflow-doc-zh/videos/
        cd ./tensorflow-doc-zh/source/assets/videos/ImperialCollegeMath/
        ls
        echo '============================================'
        git rm -rf *
        git commit -m "remove some videos"
        git push origin master
