name: tfplayground

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        cd ..
        git clone https://github.com/tensorflow/playground tfplay
        cd tfplay
        npm i
        npm run build
        
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git checkout -b tf-pages
        git commit -m 'created tf-pages'
        git subtree push --prefix dist origin tf-pages
