name: Upload Machine Learning Bases

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./01_Introduction/07_Working_with_Data_Sources/
        ls
        echo '============================================'
        cd machine-learning-bases
        wget --user-agent="Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.204 Safari/534.16" http://gdbtools.unibe.ch:8080/cdn/GDB17.50000000.smi.gz
        gunzip GDB17.50000000.smi.gz
        cd ..
        git add -A
        
        git status 
        git commit -m "Add Machine Learning Databases "
        ls
        git push origin master
